routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Producto;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    $user = Auth::user();
    if ($user) {
        return redirect('/admin');
    } else {
        return redirect('/login');
    }
});

Route::get('/home', 'AdminController@inicioAdministracion');
//Autenticacion de usuarios
Auth::routes();
//Panel
Route::get('/admin', 'AdminController@inicioAdministracion');

//PRODUCTOS
Route::get('/listar_productos', 'ProductosController@listar_view');
Route::put('/productos/enviar/{id}', 'ProductosController@enviar');
Route::resource('/productos', 'ProductosController');
Route::get('/productos_pto/{id}', 'ProductosController@productos_pto');
//USUARIOS
Route::get('/listar_usuarios', 'UsuariosController@listar_view');
Route::put('/usuarios_pass/{id}', 'UsuariosController@cambiar_pass');
Route::get('/mi_usuario', 'UsuariosController@mi_usuario');
Route::resource('/usuarios', 'UsuariosController');
//COMPRA Y VENTA
Route::get('/listar_cv', 'CompraVentasController@listar_view');
Route::get('/listar_compras', 'CompraVentasController@listar_compras');
Route::get('/listar_ventas', 'CompraVentasController@listar_ventas');

Route::resource('/cv', 'CompraVentasController');

//FACTURAS
Route::get('/listar_clientes', 'FacturasController@clientes_view');
Route::get('/listar_facturas', 'FacturasController@listar_view');
Route::put('/act_estado/{id}/', 'FacturasController@update_estado');
Route::get('/facturas/clientes', 'FacturasController@clientes');
Route::get('/facturas/ventas', 'FacturasController@ventas');
Route::get('/facturas/compras', 'FacturasController@compras');
Route::get('/facturas/compras/{f_inicio}/{f_final}', 'FacturasController@compras_rango');
Route::get('/facturas/venta/balance/{f_inicio}/{f_final}', 'FacturasController@venta_balance');
Route::get('/facturas/compra/balance/{f_inicio}/{f_final}', 'FacturasController@compra_balance');
Route::get('/facturas/ventas/{f_inicio}/{f_final}', 'FacturasController@ventas_rango');
Route::resource('/facturas', 'FacturasController');

//EMPLEADOS
Route::get('/listar_empleados', 'EmpleadosController@listar_view');
Route::resource('/empleados', 'EmpleadosController');
Route::get('empleados/detalles/{id}', 'EmpleadosController@usuario_de_empleado');
Route::get('empleados/punto/{id}', 'EmpleadosController@punto');
Route::put('empleados/asignar/{id_user}/{id_pto}', 'EmpleadosController@asignar_pto');

//PUNTO DE SERVICIO
Route::put('inventario/mod_cant/{id}', 'PuntoController@mod_cant');
Route::get('/listar_puntos', 'PuntoController@listar_view');
Route::get('/inventario/{id}', 'PuntoController@inventario');
Route::get('/inventario_punto/{id}', 'PuntoController@listar_inventario');
Route::delete('inventario/quitar_prod_inv/{id}', 'PuntoController@elimiar_prod_inventario');
Route::resource('/puntos', 'PuntoController');

//CONTRATOS 
Route::get('contratos/crear_contrato_punto', 'ContratoPuntoController@crear_contrato_view');
Route::post('contratos/crear_pto', 'ContratoPuntoController@crear_contrato');
Route::get('contratos/pto/ver/{id}', 'ContratoPuntoController@mostrar_contrato_punto');
Route::post('contratos/pto/edit/{id}', 'ContratoPuntoController@edit_contrato_punto');
Route::get('contratos/crear_contrato_empleado', 'ContratoEmpleadoController@crear_contrato_empleado_view');
Route::post('contratos/crear', 'ContratoEmpleadoController@crear');
Route::post('contratos/actualizar', 'ContratoEmpleadoController@actualizar');
Route::get('contratos/ver/{id_empleado}', 'ContratoEmpleadoController@mostrar_contrato_empleado');
Route::get('contratos/empleado/termino', 'ContratoEmpleadoController@crear_termino_empleado_view');
Route::post('contratos/empleado/termino/crear', 'ContratoEmpleadoController@crear_termino_empleado');
Route::get('contratos/empleado/termino/detalles/{id}', 'ContratoEmpleadoController@detalles_termino_empleado');
Route::delete('contratos/empleado/termino/eliminar/{id}', 'ContratoEmpleadoController@eliminar_termino_contrato_empleado');
Route::get('contratos/empleado/mostar_terminos', 'ContratoEmpleadoController@termino_empleado_view');
Route::get('contratos/empleado/termino_json', 'ContratoEmpleadoController@terminos_json');

//ASISTENCIA
Route::get('asistencia/hoy/{id_empleado}', 'AsistenciaController@hoy_view');
Route::post('asistencia/confirmar/{id}', 'AsistenciaController@asistencia_confirmada');
Route::post('asistencia/denegar/{id}', 'AsistenciaController@asistencia_denegada');
Route::get('asistencia/dias_antes/{id_empleado}', 'AsistenciaController@dias_entes_view');
Route::get('asistencia/empleado_view/{id}/{inicio}/{fin}', 'AsistenciaController@asistencia_empleado_view');
Route::get('asistencia/empleados_view', 'AsistenciaController@empleados_view');
Route::get('asistencia/empleado/{id}/{inicio}/{fin}', 'AsistenciaController@asistencia_empleado');
Route::get('asistencia/empleados', 'AsistenciaController@asistencia_empleados');
//Route::get('asistencia/general', 'AsistenciaController@asistencia_empleados');
Route::post('asistencia/hoy/informar/{id_empleado}', 'AsistenciaController@informar_hoy');
Route::post('asistencia/dia/informar/{id_empleado}', 'AsistenciaController@informar_dia');
//NOTIFICACIÓN
Route::put('notificacion/crear', 'NotificacionsController@crear');
//INFORMAR DE PERDIDAS
Route::get('perdidas/calcular/{inicio}/{fin}', 'PerdidasController@calcular_total_perdidas');
Route::get('perdidas/informar', 'PerdidasController@informar_view');
Route::get('perdidas/json', 'PerdidasController@perdidas_json');
Route::get('perdidas/listar_perdidas', 'PerdidasController@listar_view');
Route::get('perdidas/listar_perdidas_json_all', 'PerdidasController@perdidas_json_all');
Route::get('perdidas/listar_perdidas_all', 'PerdidasController@listar_view_all');
Route::post('perdidas/confirmar/{id}', 'PerdidasController@confirmar');
Route::post('perdidas/eliminar/{id}', 'PerdidasController@eliminar');
//UNIFORME
Route::resource('/uniforme','UniformeController');
Route::get('/uniforme/ver/empleados_tallas_json','UniformeController@empleados_talla_json');
Route::get('/uniforme/ver/lista_empleados','UniformeController@listar_empleados');
Route::get('/uniforme/asignar/{id}','UniformeController@asignar_view');
Route::post('/uniforme/empleado/asignar','UniformeController@guardar_uniforme_empleado');
Route::get('/uniforme/empleado/eliminar/{id}','UniformeController@eliminar_uniforme_empleado');
Route::get('/uniforme/gastos/ver','UniformeController@uniforme_gastos');
Route::get('/uniforme/gastos/calcular/{inicio}/{fin}','UniformeController@uniforme_gastos_calculo');
//NOMINA
Route::get('nomina/{id_empleado}/{inicio}/{fin}/{provida}/{anticipo}/{bono}/{otro_pago}/{otro_descuento}', 'AsistenciaController@pago_empleados');
Route::get('nomina/todos','AsistenciaController@listar');
//INFORMES
Route::resource('informe','InformesController');
Route::get('informe/calculo/empleados','InformesController@calcular_empleados');
Route::get('informe/calculo/pto','InformesController@calcular_pto_servicio');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model {

    public function user() {
        return $this->belongsTo('App\User');
    }
  

    public function punto() {
        $pto = EmpleadoPunto::where('empleado_id', $this->id)->get();
        $pto_object = Pto_Servicio::findOrFail($pto[0]->pto_servicio_id);
        return User::findOrFail($pto_object->user_id);
    }

    public function tiene_punto() {
        if (count(EmpleadoPunto::where('empleado_id', $this->id)->get()) > 0) {
            $pto = EmpleadoPunto::where('empleado_id', $this->id)->get();
            if (Pto_Servicio::findOrFail($pto[0]->pto_servicio_id)) {
                return TRUE;
            }
        } else {
            return FALSE;
        }
    }

}

app/Http/Controllers/EmpleadosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class EmpleadosController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return datatables()->collection(\App\User::all()->where('role_id', 7))->toJson();
    }

    public function asignar_pto($id_user, $id_pto) {
        $id_e = User::find($id_user);
        $id_e= $id_e->empleado->id;
        $buscar_borrar = \App\EmpleadoPunto::where('empleado_id',$id_e);
        if($buscar_borrar){
            $buscar_borrar->delete();
        }
        $id_p = User::find($id_pto);
        $id_p = $id_p->punto->id;

    
        $emp_pto = new \App\EmpleadoPunto();
        $emp_pto->empleado_id = $id_e;
        $emp_pto->pto_servicio_id = $id_p;
       
        if ( $emp_pto->save()) {
            return 'Empleado asosiado a punto de servicio correctamente';
        } else {
            return 'Ha ocurrido un error';
        }
    }

    /**
     * Show the form for creating a new resource.
     * foreach ($empleados as $e){
      var_dump($e->user()) ;
      }
     * @return \Illuminate\Http\Response
     */
    public function create() {
//
    }

    public function listar_view() {
        $puntos = \App\User::where('role_id', '=', 5)->get();
        return view('empleados\mostar', compact('puntos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
//
    }

//devuelve el empleado de un usuario con su punto de servicio vinculado
// si no tiene punto de servicio crea uno falso para mostrar el mensaje de NO TIENE
    public function usuario_de_empleado($id) {
        $emp = \App\User::findOrFail($id)->empleado;
        if ($emp->tiene_punto()) {
            $emp['punto'] = $emp->punto();
        } else {
            $pto_fake = new User();
            $pto_fake->name = 'No Tiene';
            $emp['punto'] = $pto_fake;
        }
        return $emp;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $empleado = \App\Empleado::findOrFail($id);
        $empleado['punto'] = $empleado->punto();
        return $empleado;
    }

// con el id del empleado devuelve el punto de servcio al que corresponde
    public function punto($id) {

        return $this->show($id)->punto();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
//
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
//
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
//
    }

}

resources/views/empleados/editar.blade.php
@extends('layouts.base')
@section('contenido')
<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-top-spacing" id="cancel-row">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="widget-content widget-content-area br-6">
                    <h2>Editar  Factura</h2>
                    <div class="modal-body">
                        <form  method="POST" action="{{route('facturas.update',$factura->id)}}">
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Folio</label>
                                <div class="col-sm-10">
                                    <input value="@if($factura ?? '') {{$factura->folio}} @endif" type="text" name="folio" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el Folio" disabled="disabled">
                                    <input type="hidden" name="_method" value="PUT">
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Fecha</label>
                                <div class="col-sm-10">
                                    <input value="@if($factura ?? ''){{$factura->fecha}}@endif" type="date" name="fecha" class="form-control form-control-lg" id="colFormLabelSm" required>
                                </div>
                            </div>
                            {{csrf_field()}}
                          
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Proveedor</label>
                                <div class="col-sm-10">
                                    <select id="proveedor" name="proveedor" class="form-control form-small">
                                       
                                       @if($proveedor ?? '')
                                       @foreach($proveedor ?? ''  as $p)
                                       <option value="{{$p->id}}" @if($p->id == $factura->proveedor) selected @endif>{{$p->name}}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                    <script>
                                        var formSmall = $(".form-small").select2({tags: true});
                                        formSmall.data('select2').$container.addClass('form-control-sm');</script>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Observaciones</label>
                                <div class="col-sm-10">
                                    <textarea  name="observaciones" class="form-control mb-4" rows="3" id="descripcion">@if($factura ?? ''){{$factura->observaciones}}@endif</textarea>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Valor neto</label>
                                <div class="col-sm-10">
                                    <input value="@if($factura ?? ''){{$factura->valor_neto}}@endif" type="number" name="valor_neto" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el valor del monto" required>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Estado de Pago</label>
                                <div class="col-sm-10">
                                    <select id="estado" name="estado" class="form-control form-small" required="required">
                                        
                                        <option value="Emitida" @if($factura->estado_pago == 'Emitida') selected @endif>Emitida</option>
                                        <option value="Registrada" @if($factura->estado_pago == 'Registrada') selected @endif>Registrada</option>
                                        <option value="Solicitada Anulación" @if($factura->estado_pago == 'Solicitada Anulación') selected @endif>Solicitada Anulación</option>
                                        <option value="Anulación Aceptada" @if($factura->estado_pago == 'Anulación Aceptada') selected @endif>Anulación Aceptada</option>
                                        <option value="Rechazada" @if($factura->estado_pago == 'Rechazada') selected @endif>Rechazada</option>
                                        <option value="Reenviada" @if($factura->estado_pago == 'Reenviada') selected @endif>Reenviada</option>
                                        <option value="Aceptada" @if($factura->estado_pago == 'Aceptada') selected @endif>Aceptada</option>
                                        <option value="Cobrada" @if($factura->estado_pago == 'Cobrada') selected @endif>Cobrada</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Operación</label>
                                <div class="col-sm-10">
                                    <select id="operacion" name="operacion" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione la operación</option>
                                        <option value="Compra" @if($factura->operacion == 'Compra') selected @endif>Compra</option>
                                        <option value="Venta" @if($factura->operacion == 'Venta') selected @endif>Venta</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Productos</label>
                                <div class="col-sm-10">
                                    
                                       <select id="tipo_producto" name="tipo_producto" class="form-control form-small" required="required">
                                        <option value="Maquinaria" @if($factura->tipo_producto == 'Maquinaria' ) selected @endif>Maquinaria</option>
                                        <option value="Insumos" @if($factura->tipo_producto == 'Insumos' ) selected @endif>Insumos</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <!-- Inputs especificos de clientes -->
                             <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Transacción</label>
                                <div class="col-sm-10">
                                    <select id="transaccion" name="transaccion" class="form-control form-small" required="required">
                                        
                                        <option value="Paypal" @if($factura->tipo_transaccion == 'Paypal' ) selected @endif>Paypal</option>
                                        <option value="Debito" @if($factura->tipo_transaccion == 'Debito' ) selected @endif>Debito</option>
                                        <option value="Transferencia Bancaría" @if($factura->tipo_transaccion == 'Transferencia Bancaría' ) selected @endif>Transferencia Bancaría</option>
                                        <option value="Pagos a través del móvil" @if($factura->tipo_transaccion == 'Pagos a través del móvil' ) selected @endif>Pagos a través del móvil</option>
                                        <option value="Bancos online" @if($factura->tipo_transaccion == 'Bancos online' ) selected @endif>Bancos Online</option>
                                    </select>
                                </div>
                            </div>
                            <div id="input_rubro" class="form-group row mb-4" >
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Fecha de pago</label>
                                <div class="col-sm-10">
                                    <input value="@if($factura ?? ''){{$factura->fecha_pago}}@endif" type="date" name="fecha_pago" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el rubro" >
                                </div>
                            </div>
                           
                          
                            
                            <input type="submit" class="mb-4 btn btn-primary" value="Modificar" >
                            <a href="{{url('listar_facturas')}}"> <input type="button" name="time" class="mb-4 btn btn-success" value="Cancelar" ></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    @endsection
    @section('codigos_especifico')
    <script>
        $(document).ready(function () {
            App.init();

          @if (Session::has('insertar_factura'))

                mostrar_notificacion("{{session('insertar_factura')}}");
      
        @endif



        }
        );
    </script>
    @endsection

resources/views/empleados/insertar.blade.php
@extends('layouts.base')
@section('contenido')
<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-top-spacing" id="cancel-row">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="widget-content widget-content-area br-6">
                    <h2>Insertar  Factura</h2>
                    <div class="modal-body">
                        <form action="{{url('facturas')}}" method="POST">
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Folio</label>
                                <div class="col-sm-10">
                                    <input type="text" name="folio" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el Folio" required>
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Fecha</label>
                                <div class="col-sm-10">
                                    <input type="date" name="fecha" class="form-control form-control-lg" id="colFormLabelSm" required>
                                </div>
                            </div>
                            {{ csrf_field()}}
                          
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Proveedor</label>
                                <div class="col-sm-10">
                                    <select id="proveedor" name="proveedor" class="form-control form-small">
                                       <option selected="selected" disabled="disabled">Seleccionar Proveedor</option>
                                       @if($proveedor ?? '')
                                       @foreach($proveedor ?? ''  as $p)
                                       <option value="{{$p->id}}">{{$p->name}}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                    <script>
                                        var formSmall = $(".form-small").select2({tags: true});
                                        formSmall.data('select2').$container.addClass('form-control-sm');</script>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Observaciones</label>
                                <div class="col-sm-10">
                                    <textarea name="observaciones" class="form-control mb-4" rows="3" id="descripcion"></textarea>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Valor neto</label>
                                <div class="col-sm-10">
                                    <input type="number" name="valor_neto" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el valor del monto" required>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Estado de Pago</label>
                                <div class="col-sm-10">
                                    <select id="estado" name="estado" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione el estado de la factura</option>
                                        <option value="Emitida">Emitida</option>
                                        <option value="Registrada">Registrada</option>
                                        <option value="Solicitada Anulación">Solicitada Anulación</option>
                                        <option value="Anulación Aceptada">Anulación Aceptada</option>
                                        <option value="Rechazada">Rechazada</option>
                                        <option value="Reenviada">Reenviada</option>
                                        <option value="Aceptada">Aceptada</option>
                                        <option value="Cobrada">Cobrada</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Operación</label>
                                <div class="col-sm-10">
                                    <select id="operacion" name="operacion" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione la operación</option>
                                        <option value="Compra">Compra</option>
                                        <option value="Venta">Venta</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Productos</label>
                                <div class="col-sm-10">
                                    <select id="tipo_producto" name="tipo_producto" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione la operación</option>
                                        <option value="Maquinaria">Maquinaria</option>
                                        <option value="Insumos">Insumos</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <!-- Inputs especificos de clientes -->
                             <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Transacción</label>
                                <div class="col-sm-10">
                                    <select id="transaccion" name="transaccion" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione tipo de transacción</option>
                                        <option value="Paypal">Paypal</option>
                                        <option value="Debito">Debito</option>
                                        <option value="Transferencia Bancaría">Transferencia Bancaría</option>
                                        <option value="Pagos a través del móvil">Pagos a través del móvil</option>
                                        <option value="Bancos online">Bancos Online</option>
                                    </select>
                                </div>
                            </div>
                            <div id="input_rubro" class="form-group row mb-4" >
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Fecha de pago</label>
                                <div class="col-sm-10">
                                    <input type="date" name="fecha_pago" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el rubro" >
                                </div>
                            </div>
                           
                          
                            
                            <input type="submit" name="time" class="mb-4 btn btn-primary" value="Agregar" >
                            <a href="{{url('listar_facturas')}}"> <input type="button" name="time" class="mb-4 btn btn-success" value="Cancelar" ></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    @endsection
    @section('codigos_especifico')
    <script>
        $(document).ready(function () {
            App.init();

          @if (Session::has('insertar_factura'))

                mostrar_notificacion("{{session('insertar_factura')}}");
      
        @endif



        }
        );
    </script>
    @endsection