routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Producto;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    $user = Auth::user();
    if ($user) {
        return redirect('/admin');
    } else {
        return redirect('/login');
    }
});

Route::get('/home', 'AdminController@inicioAdministracion');
//Autenticacion de usuarios
Auth::routes();
//Panel
Route::get('/admin', 'AdminController@inicioAdministracion');

//PRODUCTOS
Route::get('/listar_productos', 'ProductosController@listar_view');
Route::put('/productos/enviar/{id}', 'ProductosController@enviar');
Route::resource('/productos', 'ProductosController');
Route::get('/productos_pto/{id}', 'ProductosController@productos_pto');
//USUARIOS
Route::get('/listar_usuarios', 'UsuariosController@listar_view');
Route::put('/usuarios_pass/{id}', 'UsuariosController@cambiar_pass');
Route::get('/mi_usuario', 'UsuariosController@mi_usuario');
Route::resource('/usuarios', 'UsuariosController');
//COMPRA Y VENTA
Route::get('/listar_cv', 'CompraVentasController@listar_view');
Route::get('/listar_compras', 'CompraVentasController@listar_compras');
Route::get('/listar_ventas', 'CompraVentasController@listar_ventas');

Route::resource('/cv', 'CompraVentasController');

//FACTURAS
Route::get('/listar_clientes', 'FacturasController@clientes_view');
Route::get('/listar_facturas', 'FacturasController@listar_view');
Route::put('/act_estado/{id}/', 'FacturasController@update_estado');
Route::get('/facturas/clientes', 'FacturasController@clientes');
Route::get('/facturas/ventas', 'FacturasController@ventas');
Route::get('/facturas/compras', 'FacturasController@compras');
Route::get('/facturas/compras/{f_inicio}/{f_final}', 'FacturasController@compras_rango');
Route::get('/facturas/venta/balance/{f_inicio}/{f_final}', 'FacturasController@venta_balance');
Route::get('/facturas/compra/balance/{f_inicio}/{f_final}', 'FacturasController@compra_balance');
Route::get('/facturas/ventas/{f_inicio}/{f_final}', 'FacturasController@ventas_rango');
Route::resource('/facturas', 'FacturasController');

//EMPLEADOS
Route::get('/listar_empleados', 'EmpleadosController@listar_view');
Route::resource('/empleados', 'EmpleadosController');
Route::get('empleados/detalles/{id}', 'EmpleadosController@usuario_de_empleado');
Route::get('empleados/punto/{id}', 'EmpleadosController@punto');
Route::put('empleados/asignar/{id_user}/{id_pto}', 'EmpleadosController@asignar_pto');

//PUNTO DE SERVICIO
Route::put('inventario/mod_cant/{id}', 'PuntoController@mod_cant');
Route::get('/listar_puntos', 'PuntoController@listar_view');
Route::get('/inventario/{id}', 'PuntoController@inventario');
Route::get('/inventario_punto/{id}', 'PuntoController@listar_inventario');
Route::delete('inventario/quitar_prod_inv/{id}', 'PuntoController@elimiar_prod_inventario');
Route::resource('/puntos', 'PuntoController');

//CONTRATOS 
Route::get('contratos/crear_contrato_punto', 'ContratoPuntoController@crear_contrato_view');
Route::post('contratos/crear_pto', 'ContratoPuntoController@crear_contrato');
Route::get('contratos/pto/ver/{id}', 'ContratoPuntoController@mostrar_contrato_punto');
Route::post('contratos/pto/edit/{id}', 'ContratoPuntoController@edit_contrato_punto');
Route::get('contratos/crear_contrato_empleado', 'ContratoEmpleadoController@crear_contrato_empleado_view');
Route::post('contratos/crear', 'ContratoEmpleadoController@crear');
Route::post('contratos/actualizar', 'ContratoEmpleadoController@actualizar');
Route::get('contratos/ver/{id_empleado}', 'ContratoEmpleadoController@mostrar_contrato_empleado');
Route::get('contratos/empleado/termino', 'ContratoEmpleadoController@crear_termino_empleado_view');
Route::post('contratos/empleado/termino/crear', 'ContratoEmpleadoController@crear_termino_empleado');
Route::get('contratos/empleado/termino/detalles/{id}', 'ContratoEmpleadoController@detalles_termino_empleado');
Route::delete('contratos/empleado/termino/eliminar/{id}', 'ContratoEmpleadoController@eliminar_termino_contrato_empleado');
Route::get('contratos/empleado/mostar_terminos', 'ContratoEmpleadoController@termino_empleado_view');
Route::get('contratos/empleado/termino_json', 'ContratoEmpleadoController@terminos_json');

//ASISTENCIA
Route::get('asistencia/hoy/{id_empleado}', 'AsistenciaController@hoy_view');
Route::post('asistencia/confirmar/{id}', 'AsistenciaController@asistencia_confirmada');
Route::post('asistencia/denegar/{id}', 'AsistenciaController@asistencia_denegada');
Route::get('asistencia/dias_antes/{id_empleado}', 'AsistenciaController@dias_entes_view');
Route::get('asistencia/empleado_view/{id}/{inicio}/{fin}', 'AsistenciaController@asistencia_empleado_view');
Route::get('asistencia/empleados_view', 'AsistenciaController@empleados_view');
Route::get('asistencia/empleado/{id}/{inicio}/{fin}', 'AsistenciaController@asistencia_empleado');
Route::get('asistencia/empleados', 'AsistenciaController@asistencia_empleados');
//Route::get('asistencia/general', 'AsistenciaController@asistencia_empleados');
Route::post('asistencia/hoy/informar/{id_empleado}', 'AsistenciaController@informar_hoy');
Route::post('asistencia/dia/informar/{id_empleado}', 'AsistenciaController@informar_dia');
//NOTIFICACIÓN
Route::put('notificacion/crear', 'NotificacionsController@crear');
//INFORMAR DE PERDIDAS
Route::get('perdidas/calcular/{inicio}/{fin}', 'PerdidasController@calcular_total_perdidas');
Route::get('perdidas/informar', 'PerdidasController@informar_view');
Route::get('perdidas/json', 'PerdidasController@perdidas_json');
Route::get('perdidas/listar_perdidas', 'PerdidasController@listar_view');
Route::get('perdidas/listar_perdidas_json_all', 'PerdidasController@perdidas_json_all');
Route::get('perdidas/listar_perdidas_all', 'PerdidasController@listar_view_all');
Route::post('perdidas/confirmar/{id}', 'PerdidasController@confirmar');
Route::post('perdidas/eliminar/{id}', 'PerdidasController@eliminar');
//UNIFORME
Route::resource('/uniforme','UniformeController');
Route::get('/uniforme/ver/empleados_tallas_json','UniformeController@empleados_talla_json');
Route::get('/uniforme/ver/lista_empleados','UniformeController@listar_empleados');
Route::get('/uniforme/asignar/{id}','UniformeController@asignar_view');
Route::post('/uniforme/empleado/asignar','UniformeController@guardar_uniforme_empleado');
Route::get('/uniforme/empleado/eliminar/{id}','UniformeController@eliminar_uniforme_empleado');
Route::get('/uniforme/gastos/ver','UniformeController@uniforme_gastos');
Route::get('/uniforme/gastos/calcular/{inicio}/{fin}','UniformeController@uniforme_gastos_calculo');
//NOMINA
Route::get('nomina/{id_empleado}/{inicio}/{fin}/{provida}/{anticipo}/{bono}/{otro_pago}/{otro_descuento}', 'AsistenciaController@pago_empleados');
Route::get('nomina/todos','AsistenciaController@listar');
//INFORMES
Route::resource('informe','InformesController');
Route::get('informe/calculo/empleados','InformesController@calcular_empleados');
Route::get('informe/calculo/pto','InformesController@calcular_pto_servicio');

resources/views/pto_servcio/editar.blade.php
@extends('layouts.base')
@section('contenido')
<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-top-spacing" id="cancel-row">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="widget-content widget-content-area br-6">
                    <h2>Editar  Punto de servcio</h2>
                    <div class="modal-body">
                        <form  method="POST" action="{{route('puntos.update',$usuario->id)}}">
                             {{csrf_field()}}
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Nombre</label>
                                <div class="col-sm-10">
                                    <input value="@if($usuario ?? '') {{$usuario->name}} @endif" type="text" name="nombre" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el Nombre" >
                                    <input type="hidden" name="_method" value="PUT">
                                </div>
                            </div>
                             <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Dirección</label>
                                <div class="col-sm-10">
                                    <input value="@if($usuario ?? '') {{$usuario->direccion}} @endif" type="text" name="direccion" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca la dirección" >
                                    
                                </div>
                            </div>
                             <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Teléfono</label>
                                <div class="col-sm-10">
                                    <input value="@if($usuario ?? '') {{$usuario->telefono}} @endif" type="phone" name="telefono" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el teléfono" >
                                    
                                </div>
                            </div>
                                  <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Correo</label>
                                <div class="col-sm-10">
                                    <input value="@if($usuario ?? '') {{$usuario->email}} @endif" type="email" name="correo" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el correo" >
                                    
                                </div>
                            </div>
                            
                             <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Folio</label>
                                <div class="col-sm-10">
                                    <input value="@if($usuario ?? '') {{$punto->folio}} @endif" type="text" name="folio" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el folio"  >
                                                                        
                                </div>
                            </div>
                                <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Nombre del Encargado</label>
                                <div class="col-sm-10">
                                    <input value="@if($punto ?? '') {{$punto->nombre_encargado}} @endif" type="text" name="encargado" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el nombre del encargado" >
                                    
                                </div>
                            </div>
                             <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Cantidad de Perdonas</label>
                                <div class="col-sm-10">
                                    <input value="@if($punto ?? '') {{$punto->cant_persona}} @endif" type="text" name="cant_persona" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca la cantidad de personas" >
                                    
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Fecha</label>
                                <div class="col-sm-10">
                                    <input value="@if($punto ?? '') {{$punto->fecha_desde_antes}} @endif" type="data" name="fecha_antes" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca la cantidad de personas" >
                                    
                                </div>
                            </div>
                                       <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Supervisor</label>
                                <div class="col-sm-10">
                                    <input value="@if($punto ?? '') {{$punto->supervisor_id}} @endif" type="data" name="supervisor" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca la cantidad de personas" >
                                    
                                </div>
                            </div>
                                <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Precio Mensual</label>
                                <div class="col-sm-10">
                                    <input value="@if($punto ?? '') {{$punto->precio_mensual}} @endif" type="data" name="precio" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca la cantidad de personas" >
                                    
                                </div>
                            </div>  <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm" >Descipción</label>
                                <div class="col-sm-10">
                                  
                                    <textarea name="descripcion" class="form-control mb-4" rows="3" id="descripcion">@if($punto ?? '') {{$punto->descripcion}} @endif</textarea>
                                </div>
                            </div>
                              
                          
                            
                            <input type="submit" class="mb-4 btn btn-primary" value="Modificar" >
                            <a href="{{url('listar_puntos')}}"> <input type="button" name="time" class="mb-4 btn btn-success" value="Cancelar" ></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    @endsection
    @section('codigos_especifico')
    <script>
        $(document).ready(function () {
            App.init();

          @if (Session::has('insertar_factura'))

                mostrar_notificacion("{{session('insertar_factura')}}");
      
        @endif



        }
        );
    </script>
    @endsection

resources/views/pto_servcio/insertar.blade.php
@extends('layouts.base')
@section('contenido')
<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-top-spacing" id="cancel-row">
            <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing">
                <div class="widget-content widget-content-area br-6">
                    <h2>Insertar  Punto de Servicio</h2>
                    <div class="modal-body">
                        <form action="{{url('facturas')}}" method="POST">
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Folio</label>
                                <div class="col-sm-10">
                                    <input type="text" name="folio" class="form-control form-control-lg" id="colFormLabelSm" placeholder="Introduzca el Folio" required>
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Fecha</label>
                                <div class="col-sm-10">
                                    <input type="date" name="fecha" class="form-control form-control-lg" id="colFormLabelSm" required>
                                </div>
                            </div>
                            {{csrf_field()}}
                          
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Proveedor</label>
                                <div class="col-sm-10">
                                    <select id="proveedor" name="proveedor" class="form-control form-small">
                                       <option selected="selected" disabled="disabled">Seleccionar Proveedor</option>
                                       @if($proveedor ?? '')
                                       @foreach($proveedor ?? ''  as $p)
                                       <option value="{{$p->id}}">{{$p->name}}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                    <script>
                                        var formSmall = $(".form-small").select2({tags: true});
                                        formSmall.data('select2').$container.addClass('form-control-sm');</script>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Observaciones</label>
                                <div class="col-sm-10">
                                    <textarea name="observaciones" class="form-control mb-4" rows="3" id="descripcion"></textarea>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Valor neto</label>
                                <div class="col-sm-10">
                                    <input type="number" name="valor_neto" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el valor del monto" required>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Estado de Pago</label>
                                <div class="col-sm-10">
                                    <select id="estado" name="estado" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione el estado de la factura</option>
                                        <option value="Emitida">Emitida</option>
                                        <option value="Registrada">Registrada</option>
                                        <option value="Solicitada Anulación">Solicitada Anulación</option>
                                        <option value="Anulación Aceptada">Anulación Aceptada</option>
                                        <option value="Rechazada">Rechazada</option>
                                        <option value="Reenviada">Reenviada</option>
                                        <option value="Aceptada">Aceptada</option>
                                        <option value="Cobrada">Cobrada</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Operación</label>
                                <div class="col-sm-10">
                                    <select id="operacion" name="operacion" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione la operación</option>
                                        <option value="Compra">Compra</option>
                                        <option value="Venta">Venta</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Productos</label>
                                <div class="col-sm-10">
                                    <select id="tipo_producto" name="tipo_producto" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione la operación</option>
                                        <option value="Maquinaria">Maquinaria</option>
                                        <option value="Insumos">Insumos</option>
                                        
                                    </select>
                                </div>
                            </div>
                            <!-- Inputs especificos de clientes -->
                             <div class="form-group row mb-4">
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Tipo de Transacción</label>
                                <div class="col-sm-10">
                                    <select id="transaccion" name="transaccion" class="form-control form-small" required="required">
                                        <option disabled="disabled" selected="selected">Seleccione tipo de transacción</option>
                                        <option value="Paypal">Paypal</option>
                                        <option value="Debito">Debito</option>
                                        <option value="Transferencia Bancaría">Transferencia Bancaría</option>
                                        <option value="Pagos a través del móvil">Pagos a través del móvil</option>
                                        <option value="Bancos online">Bancos Online</option>
                                    </select>
                                </div>
                            </div>
                            <div id="input_rubro" class="form-group row mb-4" >
                                <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Fecha de pago</label>
                                <div class="col-sm-10">
                                    <input type="date" name="fecha_pago" class="form-control form-control-lg" id="colFormLabelLg" placeholder="Introduzca el rubro" >
                                </div>
                            </div>
                           
                          
                            
                            <input type="submit" name="time" class="mb-4 btn btn-primary" value="Agregar" >
                            <a href="{{url('listar_facturas')}}"> <input type="button" name="time" class="mb-4 btn btn-success" value="Cancelar" ></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    @endsection
    @section('codigos_especifico')
    <script>
        $(document).ready(function () {
            App.init();

          @if (Session::has('insertar_factura'))

                mostrar_notificacion("{{session('insertar_factura')}}");
      
        @endif



        }
        );
    </script>
    @endsection